version: 1.0.{build}
branches:
  only:
  - master
skip_branch_with_pr: true
clone_depth: 1
cache: "C:\\projects\\firenvim\\node_modules"
build: off
test: off
deploy: off
environment:
  HEADLESS: 1
  APPVEYOR: 1
install:
  - ps: Install-Product node $env:nodejs_version
  - choco --version
  - choco install firefox-dev --pre
  - ps: $env:Path += ";C:\Program Files\Firefox Developer Edition"
  - ps: Invoke-WebRequest -Uri "https://github.com/neovim/neovim/releases/download/nightly/nvim-win64.zip" -OutFile "C:\Users\appveyor\nvim-win64.zip"
  - ps: Add-Type -assembly "system.io.compression.filesystem" ; [io.compression.zipfile]::ExtractToDirectory("C:\Users\appveyor\nvim-win64.zip", "C:\Users\appveyor\nvim")
  - ps: $env:Path += ";C:\Users\appveyor\nvim\Neovim\bin"
  - node --version
  - npm --version
  - firefox --version
  - nvim --version
  - ps: New-Item -ItemType Directory -Force -Path "C:\Users\appveyor\AppData\Local\nvim"
  - ps: Set-Content -Path "C:\Users\appveyor\AppData\Local\nvim\init.vim" -Value "set rtp+=C:\projects\firenvim"
  - npm ci
  - npm run build
  - ps: New-Item -Path "HKCU:\Software\Mozilla\NativeMessagingHosts"
  - ps: New-Item -Path "HKCU:\Software\Mozilla\NativeMessagingHosts\firenvim"
  - ps: Set-Item -Path "HKCU:\Software\Mozilla\NativeMessagingHosts\firenvim\" -Value "C:\Users\me\AppData\Local\firenvim\firenvim-firefox.json"
  - npm run install_manifests
  - npm run test firefox
